# golangci-lint configuration file
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - misspell
    - lll
    - dupl

linters-settings:
  dupl:
    threshold: 100
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/jonassiebler/chatmate
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
    - path: cmd/
      linters:
        - lll
