.nh
.TH "chatmate-help" "1" "Aug 2025" "ChatMate CLI" "ChatMate Manual"

.SH NAME
chatmate-help - Help about any command


.SH SYNOPSIS
\fBchatmate help [command] [flags]\fP


.SH DESCRIPTION
Help provides help for any command in the application.
Simply type chatmate help [path to command] for full details.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for help


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	Verbose output


.SH SEE ALSO
\fBchatmate(1)\fP
